import { z } from 'zod';
import {
  ALLOWED_IMAGE_TYPES, MAX_UPLOAD_BYTES, addressLine, businessName, dateOnly, email, emptyable,
  hexColor, httpsUrl, imageFileName, mobile, money, objectId, objectKey, opaqueId, optionalProse,
  pageSlug, personName, pincode, placeName, prose, relativePath, shortText, siteUrl, storeSlug, upiId,
} from './primitives.js';

/**
 * Store configuration schemas. Every object is `.strict()`: unknown keys are rejected.
 *
 * Most of what is saved here is rendered on the public storefront, to shoppers who never
 * agreed to trust the merchant's input. Links are https-only, text cannot carry markup,
 * and image references must be keys this system generated.
 */

export const themeSchema = z
  .object({
    primaryColor: hexColor.default('#2563EB'),
    secondaryColor: hexColor.default('#0F172A'),
    buttonColor: hexColor.default('#2563EB'),
    buttonTextColor: hexColor.default('#FFFFFF'),
    backgroundColor: hexColor.default('#FFFFFF'),
    fontFamily: z.enum(['system', 'inter', 'poppins', 'dm-sans']).default('system'),
    layout: z.enum(['grid', 'list']).default('grid'),
    cornerRadius: z.enum(['none', 'small', 'medium', 'large']).default('medium'),
  })
  .strict();

const pincodePrefix = z.string().regex(/^[1-9]\d{0,5}$/, 'Use the first 1–6 digits of a pincode');

/* ───────────── Delivery ───────────── */

/**
 * Delivery settings: the delivery methods a store offers, and where it delivers.
 *
 * Saved only as a complete document (PUT /businesses/:id/delivery), never merged into.
 * Nothing here has a default: a request that leaves a field out is refused, so an update can
 * never quietly reset something the owner set elsewhere.
 *
 * Money is in paise. The store's origin for location pricing is its contact pincode.
 */

export const MAX_DELIVERY_METHODS = 5;
export const DELIVERY_ESTIMATE_TYPES = Object.freeze(['same_day', 'next_day', 'days']);
export const DELIVERY_PRICING_TYPES = Object.freeze(['free', 'flat', 'tiered']);
export const DELIVERY_TIERS = Object.freeze(['district', 'state', 'national']);

/** A method id: generated by the server when a method is first saved, then stable. */
export const deliveryMethodId = z.string().regex(/^[a-z0-9]{6,32}$/, 'Not a delivery method id');

const deliveryPricingSchema = z
  .object({
    type: z.enum(DELIVERY_PRICING_TYPES),
    flatFee: money,
    tiers: z.object({ district: money, state: money, national: money }).strict(),
    /** Orders of at least this value (after coupons) deliver free. 0 turns it off. */
    freeAbove: money,
  })
  .strict();

const deliveryEstimateSchema = z
  .object({
    type: z.enum(DELIVERY_ESTIMATE_TYPES),
    minDays: z.number().int().min(0).max(60),
    maxDays: z.number().int().min(0).max(60),
    /** Off: the estimate is neither shown to customers nor recorded on their orders. */
    show: z.boolean(),
  })
  .strict()
  .superRefine((e, ctx) => {
    if (e.type === 'days' && e.minDays < 1) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['minDays'], message: 'Use Same day for deliveries that arrive today' });
    }
    if (e.type === 'days' && e.maxDays < e.minDays) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['maxDays'], message: 'The latest day must be on or after the earliest' });
    }
  });

export const deliveryMethodSchema = z
  .object({
    /** Absent on a method being added; the server assigns one. */
    id: deliveryMethodId.optional(),
    name: shortText(1, 40, 'Method name'),
    description: shortText(0, 120, 'Description'),
    kind: z.enum(['delivery', 'pickup']),
    active: z.boolean(),
    primary: z.boolean(),
    pricing: deliveryPricingSchema,
    /** Per-area prices that override the method's own; the longest matching prefix wins. */
    pincodeRules: z.array(z.object({ pincodePrefix, fee: money }).strict()).max(200),
    estimate: deliveryEstimateSchema,
  })
  .strict()
  .superRefine((m, ctx) => {
    if (m.kind === 'pickup' && (m.pricing.type !== 'free' || m.pincodeRules.length > 0)) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['pricing', 'type'], message: 'Pickup is always free' });
    }
    if (m.pricing.type === 'flat' && m.pricing.flatFee <= 0) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['pricing', 'flatFee'], message: 'Set a delivery charge above zero, or choose Free delivery' });
    }
    if (m.pricing.type === 'free' && m.pricing.freeAbove > 0) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['pricing', 'freeAbove'], message: 'Free delivery is already free on every order' });
    }
    const prefixes = m.pincodeRules.map((r) => r.pincodePrefix);
    if (new Set(prefixes).size !== prefixes.length) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['pincodeRules'], message: 'Each pincode can only have one price' });
    }
  });

export const deliverySettingsSchema = z
  .object({
    methods: z.array(deliveryMethodSchema).min(1, 'Add at least one delivery method').max(MAX_DELIVERY_METHODS, `Up to ${MAX_DELIVERY_METHODS} delivery methods`),
    /** Where the store delivers. Empty means everywhere. Pickup is never restricted. */
    serviceablePincodePrefixes: z.array(pincodePrefix).max(500),
  })
  .strict()
  .superRefine((d, ctx) => {
    const primaries = d.methods.filter((m) => m.primary);
    if (primaries.length !== 1) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['methods'], message: 'Choose exactly one main delivery method' });
    } else if (!primaries[0].active) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['methods'], message: 'The main delivery method must be switched on' });
    }
    const ids = d.methods.map((m) => m.id).filter(Boolean);
    if (new Set(ids).size !== ids.length) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['methods'], message: 'Two delivery methods share an id' });
    }
    if (new Set(d.serviceablePincodePrefixes).size !== d.serviceablePincodePrefixes.length) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['serviceablePincodePrefixes'], message: 'A pincode is listed twice' });
    }
  });

export const paymentSettingsSchema = z
  .object({
    codEnabled: z.boolean().default(true),
    codMaxOrderValue: money.default(0),
    upiEnabled: z.boolean().default(false),
    upiId: emptyable(upiId),
    upiPayeeName: personName.optional().or(businessName.optional()),
    upiQrImageKey: objectKey.optional(),
    upiRequireUtr: z.boolean().default(true),
    upiAllowScreenshot: z.boolean().default(true),
    upiPendingExpiryMinutes: z.number().int().min(0).max(4320).default(1440),
  })
  .strict()
  .superRefine((d, ctx) => {
    if (d.upiEnabled && !d.upiId) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['upiId'], message: 'Add your UPI ID before turning on UPI payments' });
    }
    if (!d.codEnabled && !d.upiEnabled) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['codEnabled'], message: 'Keep at least one payment method switched on' });
    }
  });

export const cancellationRulesSchema = z
  .object({
    customerCancellationEnabled: z.boolean().default(true),
    latestStage: z.enum(['NEW', 'CONFIRMED', 'PREPARING', 'READY_TO_SHIP']).default('CONFIRMED'),
    graceMinutes: z.number().int().min(0).max(1440).default(30),
    requireReason: z.boolean().default(false),
  })
  .strict();

export const storePageSchema = z
  .object({
    slug: pageSlug,
    title: shortText(2, 80, 'Title'),
    /**
     * Markdown. "<" is refused outright, so no page body can ever contain an HTML tag —
     * the renderer does not have to be trusted to strip one.
     */
    body: prose(20000, { label: 'Page content' }),
    published: z.boolean().default(true),
  })
  .strict();

export const updateStoreSettingsSchema = z
  .object({
    theme: themeSchema.partial().optional(),
    banners: z
      .array(
        z
          .object({
            imageKey: objectKey,
            link: emptyable(httpsUrl),
            alt: shortText(0, 120, 'Alt text').default(''),
            sortOrder: z.number().int().min(0).max(20).default(0),
          })
          .strict(),
      )
      .max(10)
      .optional(),
    announcement: z
      .object({ text: shortText(0, 200, 'Announcement'), enabled: z.boolean() })
      .strict()
      .refine((a) => !a.enabled || a.text.length > 0, { path: ['text'], message: 'Write the announcement before turning it on' })
      .optional(),
    featuredCategoryIds: z.array(objectId).max(12).optional(),
    featuredProductIds: z.array(objectId).max(24).optional(),
    sections: z
      .array(
        z
          .object({
            type: z.enum(['new_arrivals', 'best_sellers', 'sale', 'featured']),
            enabled: z.boolean(),
            title: shortText(1, 60, 'Section title'),
            sortOrder: z.number().int().min(0).max(20),
          })
          .strict(),
      )
      .max(8)
      .optional(),
    social: z
      .object({
        instagram: emptyable(siteUrl(['instagram.com'], 'Instagram')),
        facebook: emptyable(siteUrl(['facebook.com', 'fb.com'], 'Facebook')),
        youtube: emptyable(siteUrl(['youtube.com', 'youtu.be'], 'YouTube')),
        x: emptyable(siteUrl(['x.com', 'twitter.com'], 'X')),
        website: emptyable(httpsUrl),
      })
      .strict()
      .optional(),
    footerText: optionalProse(500, { label: 'Footer text' }),
    payments: paymentSettingsSchema.optional(),
    // Delivery is not part of this patch: it is saved whole through its own endpoint.
    cancellation: cancellationRulesSchema.optional(),
    pages: z
      .array(storePageSchema)
      .max(20)
      .refine((pages) => new Set(pages.map((p) => p.slug)).size === pages.length, 'Two pages share the same link')
      .optional(),
    orderingPaused: z.boolean().optional(),
    orderingPausedMessage: optionalProse(200, { multiline: false, label: 'Paused message' }),
  })
  .strict();

export const updateBusinessSchema = z
  .object({
    name: businessName.optional(),
    description: optionalProse(500, { label: 'Description' }),
    /** null removes the logo; the storefront then shows the store's name instead. */
    logoKey: objectKey.nullable().optional(),
    faviconKey: objectKey.optional(),
    contact: z
      .object({
        email: emptyable(email),
        phone: mobile.optional(),
        whatsapp: mobile.optional(),
        addressLine: addressLine(2, 200).optional().or(z.literal('')),
        city: placeName.optional().or(z.literal('')),
        state: placeName.optional().or(z.literal('')),
        pincode: emptyable(pincode),
      })
      .strict()
      .optional(),
  })
  .strict();

/* ───────────── Policies ───────────── */

/**
 * The four customer-facing policy documents. Fixed: a store cannot add a fifth. `slug` is the
 * storefront address (/policies/<slug>); `title` is the standard name a new document starts with.
 */
export const POLICY_DOCUMENTS = Object.freeze({
  privacy: Object.freeze({ slug: 'privacy-policy', title: 'Privacy Policy' }),
  terms: Object.freeze({ slug: 'terms', title: 'Terms & Conditions' }),
  refund: Object.freeze({ slug: 'refund-policy', title: 'Refund & Cancellation Policy' }),
  shipping: Object.freeze({ slug: 'shipping-policy', title: 'Shipping & Delivery Policy' }),
});
export const POLICY_TYPES = Object.freeze(Object.keys(POLICY_DOCUMENTS));
export const policyType = z.enum(POLICY_TYPES, { errorMap: () => ({ message: 'Unknown policy' }) });

/**
 * A policy's text. Markdown-style plain text: "<" is refused (prose), so no document can ever
 * carry an HTML tag, and the storefront renders it as text. 10,000 characters is a long policy;
 * four of them stay well inside the settings item's size.
 */
export const POLICY_MAX_CHARS = 10000;
export const RETURN_WINDOW_MAX_DAYS = 365;

/**
 * One document's changes. Every field is optional and there are no defaults: what is sent is
 * changed, what is left out is kept, so saving one document never touches another.
 */
export const policyDocumentPatchSchema = z
  .object({
    enabled: z.boolean({ invalid_type_error: 'Choose whether customers can see it' }).optional(),
    title: shortText(2, 80, 'Title').optional(),
    content: prose(POLICY_MAX_CHARS, { label: 'Policy text' }).optional(),
  })
  .strict();

export const updatePoliciesSchema = z
  .object({
    /** The return rule customers see: "[N]-day return policy", or "No returns allowed". */
    trade: z
      .object({
        returnsAllowed: z.boolean({ invalid_type_error: 'Choose whether you accept returns' }).optional(),
        returnWindowDays: z
          .number({ invalid_type_error: 'Enter the number of days' })
          .int('Enter whole days')
          .min(1, 'The return window is at least 1 day')
          .max(RETURN_WINDOW_MAX_DAYS, `The return window is at most ${RETURN_WINDOW_MAX_DAYS} days`)
          .optional(),
      })
      .strict()
      .optional(),
    documents: z
      .object(Object.fromEntries(POLICY_TYPES.map((type) => [type, policyDocumentPatchSchema.optional()])))
      .strict()
      .optional(),
  })
  .strict()
  .refine((v) => v.trade !== undefined || v.documents !== undefined, 'Nothing to save');

/** Changing a slug breaks every shared link, so it is separate and heavily rate limited. */
export const changeSlugSchema = z
  .object({
    slug: storeSlug,
    confirm: z.literal(true, { errorMap: () => ({ message: 'Confirm that existing links will stop working' }) }),
  })
  .strict();

/* ───────────── Uploads ───────────── */

export const uploadAuthorizationSchema = z
  .object({
    purpose: z.enum(['product', 'category', 'logo', 'banner', 'favicon', 'qr', 'payment_proof']),
    contentType: z.enum(ALLOWED_IMAGE_TYPES),
    sizeBytes: z.number().int().min(1).max(MAX_UPLOAD_BYTES, 'Images must be 8MB or smaller'),
    /** Extension hint only. The storage key is always generated on the server. */
    originalName: imageFileName.optional(),
    checksumSha256: z.string().regex(/^[a-f0-9]{64}$/, 'Invalid checksum').optional(),
    productId: objectId.optional(),
  })
  .strict()
  .refine((v) => v.purpose === 'product' || !v.productId, {
    path: ['productId'],
    message: 'Only product images belong to a product',
  });

export const confirmUploadSchema = z
  .object({
    uploadId: objectId,
    width: z.number().int().positive().max(20000).optional(),
    height: z.number().int().positive().max(20000).optional(),
  })
  .strict();

/* ───────────── Analytics ───────────── */

export const trackEventSchema = z
  .object({
    event: z.enum([
      'store_view', 'page_view', 'product_view', 'category_view', 'search',
      'add_to_cart', 'remove_from_cart', 'checkout_started', 'checkout_failed', 'coupon_applied',
    ]),
    /** Rotating anonymous client id. Never linked to a customer record. */
    sessionId: opaqueId(8, 64, 'Session'),
    path: relativePath.optional(),
    productId: objectId.optional(),
    categoryId: objectId.optional(),
    searchTerm: shortText(0, 120, 'Search').optional(),
    quantity: z.number().int().min(1).max(99).optional(),
    /** Only the referring origin is useful, and only an http(s) one is real. */
    referrer: z.string().max(300).regex(/^https?:\/\/[A-Za-z0-9.-]+(?::\d{1,5})?(?:\/[^\s<>"]*)?$/, 'Invalid referrer').optional(),
  })
  .strict();

export const trackEventBatchSchema = z
  .object({
    events: z.array(trackEventSchema).min(1).max(20),
  })
  .strict();

export const analyticsQuerySchema = z
  .object({
    from: dateOnly.optional(),
    to: dateOnly.optional(),
    preset: z.enum(['today', 'yesterday', '7d', '30d', '90d', 'custom']).default('7d'),
  })
  .strict()
  .refine((v) => v.preset !== 'custom' || (v.from && v.to), {
    path: ['from'],
    message: 'Choose both a start and an end date',
  })
  .refine((v) => !v.from || !v.to || v.from <= v.to, {
    path: ['to'],
    message: 'The end date must be on or after the start date',
  });
