/**
 * Canonical error codes. Clients switch on `code`, never on the message text,
 * so copy can change without breaking an app in the field.
 */
export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  VARIANT_UNAVAILABLE: 'VARIANT_UNAVAILABLE',
  CART_EMPTY: 'CART_EMPTY',
  TOTAL_MISMATCH: 'TOTAL_MISMATCH',

  COUPON_INVALID: 'COUPON_INVALID',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
  COUPON_USAGE_EXCEEDED: 'COUPON_USAGE_EXCEEDED',
  COUPON_MIN_ORDER_NOT_MET: 'COUPON_MIN_ORDER_NOT_MET',

  DELIVERY_UNAVAILABLE: 'DELIVERY_UNAVAILABLE',
  PAYMENT_METHOD_UNAVAILABLE: 'PAYMENT_METHOD_UNAVAILABLE',
  PAYMENT_ALREADY_SETTLED: 'PAYMENT_ALREADY_SETTLED',
  DUPLICATE_UTR: 'DUPLICATE_UTR',

  ORDER_TRANSITION_INVALID: 'ORDER_TRANSITION_INVALID',
  ORDER_CANCELLATION_NOT_ALLOWED: 'ORDER_CANCELLATION_NOT_ALLOWED',
  ORDERING_PAUSED: 'ORDERING_PAUSED',

  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_INACTIVE: 'STORE_INACTIVE',
  SLUG_TAKEN: 'SLUG_TAKEN',

  DOMAIN_INVALID: 'DOMAIN_INVALID',
  DOMAIN_TAKEN: 'DOMAIN_TAKEN',
  DOMAIN_NOT_VERIFIED: 'DOMAIN_NOT_VERIFIED',

  EMAIL_TAKEN: 'EMAIL_TAKEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  SESSION_REUSE_DETECTED: 'SESSION_REUSE_DETECTED',

  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  UPLOAD_REJECTED: 'UPLOAD_REJECTED',
  STORAGE_QUOTA_EXCEEDED: 'STORAGE_QUOTA_EXCEEDED',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
});

/** Friendly fallback copy so every surface shows the same wording for a given code. */
export const ERROR_MESSAGES = Object.freeze({
  VALIDATION_ERROR: 'Some details need attention.',
  UNAUTHENTICATED: 'Please sign in to continue.',
  FORBIDDEN: 'You do not have access to this.',
  NOT_FOUND: 'We could not find what you were looking for.',
  RATE_LIMITED: 'Too many attempts. Please wait a moment.',
  PRODUCT_OUT_OF_STOCK: 'This item just went out of stock.',
  COUPON_INVALID: 'That coupon code is not valid for this store.',
  COUPON_EXPIRED: 'That coupon has expired.',
  COUPON_MIN_ORDER_NOT_MET: 'Your order does not meet this coupon’s minimum value.',
  DELIVERY_UNAVAILABLE: 'We do not deliver to this pincode yet.',
  ORDERING_PAUSED: 'This store is not taking orders right now.',
  DUPLICATE_UTR: 'This payment reference was already submitted.',
  INTERNAL_ERROR: 'Something went wrong. Please try again.',
});

export const messageForCode = (code) => ERROR_MESSAGES[code] ?? ERROR_MESSAGES.INTERNAL_ERROR;
